/* TPL_HEADER_START */
/* -*- Mode: C{} c-basic-offset:4 {} -*- */
/*
 *  (C) 2018 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated. DO NOT EDIT.
 */

#include <shmem.h>
#include "oshmpi_impl.h"
/* TPL_HEADER_END */

TYPE shmem_TYPENAME_atomic_fetch_and(TYPE * dest, TYPE value, int pe)
{
    TYPE oldval;
    OSHMPI_ctx_fetch_and(SHMEM_CTX_DEFAULT, MPI_TYPE, &value /* origin_addr */ ,
                         &oldval /*result_addr */ , dest /* target_addr */ , pe);
    return oldval;
}

TYPE shmem_ctx_TYPENAME_atomic_fetch_and(shmem_ctx_t ctx, TYPE * dest, TYPE value, int pe)
{
    TYPE oldval;
    OSHMPI_ctx_fetch_and(ctx, MPI_TYPE, &value /* origin_addr */ ,
                         &oldval /*result_addr */ , dest /* target_addr */ , pe);
    return oldval;
}

void shmem_TYPENAME_atomic_and(TYPE * dest, TYPE value, int pe)
{
    OSHMPI_ctx_and(SHMEM_CTX_DEFAULT, MPI_TYPE, &value /* origin_addr */ , dest /* target_addr */ ,
                   pe);
}

void shmem_ctx_TYPENAME_atomic_and(shmem_ctx_t ctx, TYPE * dest, TYPE value, int pe)
{
    OSHMPI_ctx_and(ctx, MPI_TYPE, &value /* origin_addr */ , dest /* target_addr */ , pe);
}

TYPE shmem_TYPENAME_atomic_fetch_or(TYPE * dest, TYPE value, int pe)
{
    TYPE oldval;
    OSHMPI_ctx_fetch_or(SHMEM_CTX_DEFAULT, MPI_TYPE, &value /* origin_addr */ ,
                        &oldval /*result_addr */ , dest /* target_addr */ , pe);
    return oldval;
}

TYPE shmem_ctx_TYPENAME_atomic_fetch_or(shmem_ctx_t ctx, TYPE * dest, TYPE value, int pe)
{
    TYPE oldval;
    OSHMPI_ctx_fetch_and(ctx, MPI_TYPE, &value /* origin_addr */ ,
                         &oldval /*result_addr */ , dest /* target_addr */ , pe);
    return oldval;
}

void shmem_TYPENAME_atomic_or(TYPE * dest, TYPE value, int pe)
{
    OSHMPI_ctx_or(SHMEM_CTX_DEFAULT, MPI_TYPE, &value /* origin_addr */ , dest /* target_addr */ ,
                  pe);
}

void shmem_ctx_TYPENAME_atomic_or(shmem_ctx_t ctx, TYPE * dest, TYPE value, int pe)
{
    OSHMPI_ctx_or(ctx, MPI_TYPE, &value /* origin_addr */ , dest /* target_addr */ , pe);
}

TYPE shmem_TYPENAME_atomic_fetch_xor(TYPE * dest, TYPE value, int pe)
{
    TYPE oldval;
    OSHMPI_ctx_fetch_xor(SHMEM_CTX_DEFAULT, MPI_TYPE, &value /* origin_addr */ ,
                         &oldval /*result_addr */ , dest /* target_addr */ , pe);
    return oldval;
}

TYPE shmem_ctx_TYPENAME_atomic_fetch_xor(shmem_ctx_t ctx, TYPE * dest, TYPE value, int pe)
{
    TYPE oldval;
    OSHMPI_ctx_fetch_xor(ctx, MPI_TYPE, &value /* origin_addr */ ,
                         &oldval /*result_addr */ , dest /* target_addr */ , pe);
    return oldval;
}

void shmem_TYPENAME_atomic_xor(TYPE * dest, TYPE value, int pe)
{
    OSHMPI_ctx_xor(SHMEM_CTX_DEFAULT, MPI_TYPE, &value /* origin_addr */ , dest /* target_addr */ ,
                   pe);
}

void shmem_ctx_TYPENAME_atomic_xor(shmem_ctx_t ctx, TYPE * dest, TYPE value, int pe)
{
    OSHMPI_ctx_xor(ctx, MPI_TYPE, &value /* origin_addr */ , dest /* target_addr */ , pe);
}
