/* TPL_HEADER_START */
/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*
 *  (C) 2018 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated. DO NOT EDIT.
 */

#include <shmem.h>
#include "oshmpi_impl.h"
/* TPL_HEADER_END */

void shmem_TYPENAME_wait_until(TYPE * ivar, int cmp, TYPE cmp_value)
{
    /* Does not return until ivar satisfies the condition implied by cmp and cmp_value. */
    OSHMPI_WAIT_UNTIL(ivar, cmp, cmp_value, TYPE, MPI_TYPE);
}

int shmem_TYPENAME_test(TYPE * ivar, int cmp, TYPE cmp_value)
{
    int test_ret = 0;
    /* Returns 1 if the comparison evaluates to true; otherwise, returns 0. */
    OSHMPI_TEST(ivar, cmp, cmp_value, TYPE, MPI_TYPE, test_ret);
    return test_ret;
}
