/* TPL_HEADER_START */
/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*
 *  (C) 2018 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated. DO NOT EDIT.
 */

#include <shmem.h>
#include "oshmpi_impl.h"
/* TPL_HEADER_END */

void shmem_TYPENAME_wait_until(TYPE * ivar, int cmp, TYPE cmp_value)
{
    OSHMPI_ERR_ABORT("Unsupported function: %s\n", __FUNCTION__);
}

int shmem_TYPENAME_test(TYPE * ivar, int cmp, TYPE cmp_value)
{
    OSHMPI_ERR_ABORT("Unsupported function: %s\n", __FUNCTION__);
    return 0;
}
